Repository GoogleContainerTools/kaniko, pull requests merged in 2018-08, with the labels that each got.

#305 Update go-containerregistry.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
  vendor/github.com/google/go-containerregistry/pkg/v1/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/manifest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/platform.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/zz_deepcopy_generated.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: size/XXL

#289 Always snapshot files in COPY and RUN commands
  README.md
  integration/dockerfiles/Dockerfile_test_copy_same_file_many_times
  integration/integration_test.go
  pkg/commands/volume.go
  pkg/commands/workdir.go
  pkg/executor/build.go
  pkg/snapshot/layered_map.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
  pkg/util/tar_util.go
  pkg/util/tar_util_test.go
  pkg/util/util.go
  testutil/util.go
Labels: size/L

#318 Remove some constraints from our Gopkg.toml.
  Gopkg.lock
  Gopkg.toml
Labels: size/S

#319 Snapshot only specific files for COPY
  pkg/commands/add.go
  pkg/commands/copy.go
  pkg/util/fs_util.go
  pkg/util/tar_util.go
Labels: size/M

#321 Enable shared config for s3
  pkg/buildcontext/s3.go
Labels: size/XS

#323 support multiple tags when writing to a tarfile
  Gopkg.lock
  pkg/executor/push.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: size/XXL

#324 Build each kaniko image separately
  deploy/cloudbuild.yaml
Labels: size/XS

#328 Updated created by time for built image
  pkg/executor/build.go
Labels: size/XS

#327 Configure logs to show colors
  cmd/executor/cmd/root.go
  pkg/util/util.go
Labels: size/XS

#326 Extract filesystem in order rather than in reverse
  integration/dockerfiles/Dockerfile_hardlink_base
  integration/dockerfiles/Dockerfile_test_hardlink
  integration/dockerfiles/Dockerfile_test_mv_add
  integration/integration_test.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
  pkg/util/tar_util.go
Labels: size/L

#311 Separate --insecure-skip-tls-verify flag into two separate flags
  README.md
  cmd/executor/cmd/root.go
  pkg/executor/push.go
  pkg/options/options.go
Labels: lgtm, needs-ok-to-test, size/M

#330 Make sure paths are absolute before matching files to wildcard sources
  pkg/util/command_util.go
  pkg/util/command_util_test.go
  pkg/util/fs_util.go
Labels: size/S
