Repository GoogleContainerTools/kaniko, pull requests merged in 2018-11, with the labels that each got.

#397 More cache cleanups:
  pkg/cache/cache.go
  pkg/commands/base_command.go
  pkg/commands/commands.go
  pkg/commands/run.go
  pkg/executor/build.go
Labels: size/L

#423 Preserve options when doing a cache push
  pkg/executor/push.go
Labels: needs-ok-to-test, size/XS

#436 Update CHANGELOG and Makefile for v0.6.0
  CHANGELOG.md
  Makefile
Labels: size/S

#440 Skip unpacking the base FS if there are no run commands (or only cach…
  pkg/commands/base_command.go
  pkg/commands/commands.go
  pkg/commands/run.go
  pkg/executor/build.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: size/M

#443 Improve cache layer uploads.
  pkg/commands/base_command.go
  pkg/commands/commands.go
  pkg/commands/run.go
  pkg/executor/build.go
  pkg/executor/push.go
Labels: size/M

#445 Hide --azure-container-registry-config flag
  cmd/executor/cmd/root.go
Labels: needs-ok-to-test, size/XS

#447 Check if command is nil before optimizing
  pkg/executor/build.go
Labels: size/XS

#451 Make snapshotting faster by using filepath.SkipDir.
  pkg/snapshot/snapshot.go
  pkg/util/fs_util.go
Labels: size/S

#456 Fix bug in extracting hardlinks in multistage builds
  integration/dockerfiles/Dockerfile_test_hardlink
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: size/S

#461 Only return filepath.SkipDir for directories
  integration/dockerfiles/Dockerfile_test_whitelist
  pkg/snapshot/snapshot.go
Labels: size/S

#386 Cleanup readme
  README.md
Labels: needs-ok-to-test, size/L

#470 Remove support for .dockerignore
  cmd/executor/cmd/root.go
  integration/integration_test.go
Labels: size/M

#467 Fix --cleanup description
  README.md
Labels: needs-ok-to-test, size/XS

#448 Add benchmarking code
  DEVELOPMENT.md
  cmd/executor/cmd/root.go
  integration/images.go
  integration/integration_test.go
  pkg/executor/build.go
  pkg/timing/timing.go
Labels: size/M
