Repository GoogleContainerTools/kaniko, pull requests merged in 2018-12, with the labels that each got.

#476 Add to contributing guide: standards and finding something to work
  CONTRIBUTING.md
Labels: size/M

#479 Add support for COPY --from=<an unrelated image>.
  integration/dockerfiles/Dockerfile_test_multistage
  pkg/dockerfile/dockerfile.go
  pkg/executor/build.go
  pkg/util/image_util.go
  pkg/util/image_util_test.go
Labels: size/M

#483 Avoid the cachedImage/remoteImage call loop
  pkg/executor/build.go
  pkg/util/image_util.go
  pkg/util/image_util_test.go
Labels: size/S

#474 Fix intermediate layer caching
  pkg/executor/build.go
  pkg/executor/build_test.go
Labels: needs-ok-to-test, size/L

#485 Add changelog and bump version to 0.7.0
  CHANGELOG.md
  Makefile
Labels: size/S

#486 Add support for .dockerignore file
  cmd/executor/cmd/root.go
  integration/.dockerignore
  integration/dockerfiles/Dockerfile_test_dockerignore
  integration/dockerignore.go
  integration/ignore/bar
  integration/ignore/baz
  integration/ignore/foo
  integration/integration_test.go
  pkg/commands/copy.go
  pkg/constants/constants.go
  pkg/dockerfile/dockerfile.go
  pkg/executor/build.go
  pkg/util/command_util.go
  pkg/util/command_util_test.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: size/L

#488 Adding TTL to caching
  cmd/executor/cmd/root.go
  integration/images.go
  integration/integration_test.go
  pkg/cache/cache.go
  pkg/config/options.go
  pkg/executor/push.go
Labels: size/M

#487 Add more benchmarks
  pkg/executor/build.go
Labels: size/XS

#498 Deflake the meta_arg_test by setting a specific timestamp in touch.
  .travis.yml
  integration/dockerfiles/Dockerfile_test_meta_arg
Labels: size/XS

#499 Refactor tests and make them run in parallel.
  integration/integration_test.go
Labels: size/L
