Repository GoogleContainerTools/kaniko, pull requests merged in 2018-09, with the labels that each got.

#340 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/S

#336 Add CacheCommand to DockerCommand interface
  pkg/commands/add.go
  pkg/commands/arg.go
  pkg/commands/cmd.go
  pkg/commands/commands.go
  pkg/commands/copy.go
  pkg/commands/entrypoint.go
  pkg/commands/env.go
  pkg/commands/expose.go
  pkg/commands/healthcheck.go
  pkg/commands/label.go
  pkg/commands/onbuild.go
  pkg/commands/run.go
  pkg/commands/shell.go
  pkg/commands/stopsignal.go
  pkg/commands/user.go
  pkg/commands/volume.go
  pkg/commands/workdir.go
  pkg/executor/build.go
Labels: size/L

#320 Added a KanikoStage type for each stage of a Dockerfile
  cmd/executor/cmd/root.go
  pkg/config/args.go
  pkg/config/options.go
  pkg/config/stage.go
  pkg/dockerfile/dockerfile.go
  pkg/dockerfile/dockerfile_test.go
  pkg/executor/build.go
  pkg/executor/push.go
  pkg/util/image_util.go
  pkg/util/image_util_test.go
  testutil/constants.go
Labels: size/L

#337 Add Key() to LayeredMap and Snapshotter
  pkg/executor/build.go
  pkg/snapshot/layered_map.go
  pkg/snapshot/layered_map_test.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
  pkg/util/util.go
Labels: size/L

#349 Replace gometalinter with GolangCI-Lint
  cmd/executor/cmd/root.go
  hack/boilerplate/boilerplate.py
  hack/gometalinter.json
  hack/install_golint.sh
  hack/linter.sh
  integration/integration_test.go
  pkg/buildcontext/buildcontext.go
  pkg/buildcontext/s3.go
  pkg/commands/shell.go
  pkg/commands/user_test.go
  pkg/config/options.go
  pkg/config/stage.go
  pkg/dockerfile/buildargs.go
  pkg/dockerfile/dockerfile.go
  pkg/dockerfile/dockerfile_test.go
  pkg/executor/push.go
  pkg/util/bucket_util.go
  pkg/util/command_util.go
  pkg/util/command_util_test.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
  pkg/util/image_util.go
  pkg/util/tar_util.go
  test.sh
Labels: size/XL

#347 Whitelist /etc/mtab
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: size/XS

#343 Refactor build into stageBuilder type
  pkg/config/stage.go
  pkg/dockerfile/dockerfile.go
  pkg/executor/build.go
Labels: size/L

#356 Suppress usage upon Run error
  cmd/executor/cmd/root.go
  pkg/config/args.go
Labels: size/S

#353 Add layer caching to kaniko
  cmd/executor/cmd/root.go
  integration/dockerfiles/Dockerfile_test_cache
  integration/dockerfiles/Dockerfile_test_cache_install
  integration/images.go
  integration/integration_test.go
  pkg/cache/cache.go
  pkg/config/options.go
  pkg/executor/build.go
  pkg/executor/push.go
  pkg/util/fs_util.go
Labels: size/L

#364 Update README to add information about layer caching
  README.md
Labels: size/S

#363 Only return stdout when running commands for integration tests
  integration/cmd.go
Labels: size/S

#360 Enable overwriting of links (solves #351)
  integration/dockerfiles/Dockerfile_test_replaced_hardlinks
  integration/dockerfiles/Dockerfile_test_replaced_symlinks
  pkg/util/fs_util.go
Labels: size/S

#341 set default HOME env properly
  integration/dockerfiles/Dockerfile_test_user_run
  pkg/commands/run.go
  pkg/commands/run_test.go
Labels: size/S

#367 Add a benchmark package to store and monitor timings.
  pkg/timing/timing.go
  pkg/timing/timing_test.go
Labels: size/L

#369 Whitelist /busybox in the debug image
  deploy/Dockerfile_debug
Labels: needs-ok-to-test, size/XS

#370 Add a new flag to cleanup the filesystem at the end
  README.md
  cmd/executor/cmd/root.go
  pkg/config/options.go
  pkg/executor/build.go
Labels: needs-ok-to-test, size/S

#371 Fixes a whitelist issue when untarring files in ADD commands.
  Gopkg.lock
  integration/context/tars/sys.tar.gz
  integration/dockerfiles/Dockerfile_test_add
  integration/integration_test.go
  pkg/util/fs_util.go
  testutil/util.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/format.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/reporter.go
  vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
  vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
Labels: size/XXL

#374 Check --cache-repo is provided with --cache and --no-push
  cmd/executor/cmd/root.go
Labels: size/S
