Repository GoogleContainerTools/kaniko, pull requests merged in 2018-10, with the labels that each got.

#376 Update go-containerregistry dep and remove unnecessary Options
  Gopkg.lock
  pkg/executor/build.go
  pkg/executor/push.go
  vendor/github.com/google/go-containerregistry/pkg/v1/daemon/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/rebase.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/delete.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
Labels: size/M

#334 Fix handling of the volume directive
  integration/dockerfiles/Dockerfile_test_volume
  integration/dockerfiles/Dockerfile_test_volume_2
  integration/integration_test.go
  pkg/commands/volume.go
  pkg/constants/constants.go
  pkg/executor/build.go
  pkg/snapshot/snapshot.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: needs-ok-to-test, size/L

#378 Fix travis @ HEAD
  integration/integration_test.go
Labels: size/XS

#381 Don't cut everything after an equals sign
  pkg/dockerfile/buildargs.go
Labels: needs-ok-to-test, size/XS

#375 Rework cache key generation a bit.
  pkg/commands/add.go
  pkg/commands/arg.go
  pkg/commands/base_command.go
  pkg/commands/cmd.go
  pkg/commands/cmd_test.go
  pkg/commands/commands.go
  pkg/commands/copy.go
  pkg/commands/entrypoint.go
  pkg/commands/entrypoint_test.go
  pkg/commands/env.go
  pkg/commands/env_test.go
  pkg/commands/expose.go
  pkg/commands/expose_test.go
  pkg/commands/healthcheck.go
  pkg/commands/label.go
  pkg/commands/onbuild.go
  pkg/commands/onbuild_test.go
  pkg/commands/run.go
  pkg/commands/shell.go
  pkg/commands/shell_test.go
  pkg/commands/stopsignal.go
  pkg/commands/stopsignal_test.go
  pkg/commands/user.go
  pkg/commands/user_test.go
  pkg/commands/volume.go
  pkg/commands/workdir.go
  pkg/executor/build.go
  pkg/executor/composite_cache.go
Labels: size/L

#382 chore: fix broken markdown (CHANGELOG.md)
  CHANGELOG.md
Labels: needs-ok-to-test, size/XS

#385 Refactor the build loop.
  pkg/commands/volume.go
  pkg/commands/volume_test.go
  pkg/constants/constants.go
  pkg/executor/build.go
Labels: size/L

#388 Update go-containerregistry dependency
  Gopkg.lock
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/compressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/uncompressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
Labels: size/M

#383 Persistent volume caching for base images
  Makefile
  cmd/executor/cmd/root.go
  cmd/warmer/cmd/root.go
  cmd/warmer/main.go
  deploy/Dockerfile_warmer
  examples/kaniko-cache-claim.yaml
  examples/kaniko-cache-volume.yaml
  examples/kaniko-test.yaml
  examples/kaniko-warmer.yaml
  integration-test.sh
  integration/images.go
  integration/integration_test.go
  pkg/cache/cache.go
  pkg/cache/warm.go
  pkg/config/options.go
  pkg/executor/build.go
  pkg/util/image_util.go
  pkg/util/image_util_test.go
Labels: size/L

#390 Improve IsDestDir functionality with filesystem info
  pkg/util/command_util.go
Labels: needs-ok-to-test, size/XS

#393 Change loglevel for copying files to debug (#303)
  pkg/util/fs_util.go
Labels: needs-ok-to-test, size/XS

#387 Use only the necessary files in the cache keys.
  pkg/commands/add.go
  pkg/commands/base_command.go
  pkg/commands/commands.go
  pkg/commands/copy.go
  pkg/executor/build.go
  pkg/executor/composite_cache.go
Labels: size/L

#396 fix mispell
  integration/gcs.go
Labels: needs-ok-to-test, size/XS

#399 Release v0.5.0
  CHANGELOG.md
Labels: size/S

#389 Fix symlink extraction
  integration/dockerfiles/Dockerfile_test_extraction
  pkg/util/fs_util.go
Labels: size/XS

#401 Support insecure pull
  cmd/executor/cmd/root.go
  pkg/config/options.go
  pkg/executor/push.go
  pkg/util/image_util.go
  pkg/util/image_util_test.go
Labels: needs-ok-to-test, size/M

#412 adding the cache warmer to the release process
  deploy/cloudbuild-release.yaml
  deploy/cloudbuild.yaml
Labels: size/S

#414 "Container Builder" - > "Cloud Build"
  README.md
Labels: size/XS

#409 Separate Insecure Pull Options
  README.md
  cmd/executor/cmd/root.go
  pkg/config/options.go
  pkg/util/image_util.go
Labels: size/M

#413 Use remoteImage function when getting digest for cache
  pkg/util/image_util.go
Labels: size/XS

#418 fix releasing the cache warmer
  deploy/Dockerfile_warmer
Labels: size/XS

#419 Update README
  README.md
  run_in_docker.sh
Labels: size/M

#420 Update go-containerregistry
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/basic.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
Labels: size/S

#394 Add support for .dockerignore file
  cmd/executor/cmd/root.go
  integration/dockerfiles/Dockerfile_test_ignore
  integration/images.go
  pkg/dockerfile/dockerfile.go
Labels: size/L

#421 adding documentation for base image caching
  README.md
Labels: size/S

#424 Fix bugs with .dockerignore and improve integration test
  cmd/executor/cmd/root.go
  integration/dockerignore.go
  integration/images.go
  integration/integration_test.go
  pkg/constants/constants.go
  pkg/dockerfile/dockerfile.go
Labels: size/L
