Repository GoogleContainerTools/kaniko, pull requests merged in 2019-01, with the labels that each got.

#491 Adds COPY --from=previous stage name/number validation
  pkg/executor/build.go
Labels: needs-ok-to-test, size/S

#500 Adding capability to get Dockerfile from URL.
  cmd/executor/cmd/root.go
  pkg/dockerfile/dockerfile.go
Labels: needs-ok-to-test, size/S

#504 Even faster snapshotting with godirwalk.
  Gopkg.lock
  pkg/snapshot/snapshot.go
  vendor/github.com/karrick/godirwalk/LICENSE
  vendor/github.com/karrick/godirwalk/dirent.go
  vendor/github.com/karrick/godirwalk/doc.go
  vendor/github.com/karrick/godirwalk/readdir.go
  vendor/github.com/karrick/godirwalk/readdir_unix.go
  vendor/github.com/karrick/godirwalk/readdir_windows.go
  vendor/github.com/karrick/godirwalk/walk.go
  vendor/github.com/karrick/godirwalk/withFileno.go
  vendor/github.com/karrick/godirwalk/withIno.go
  vendor/github.com/karrick/godirwalk/withNamlen.go
  vendor/github.com/karrick/godirwalk/withoutNamlen.go
Labels: size/XL

#505 Change the CI cloudbuild to stop tagging latest.
  deploy/cloudbuild.yaml
Labels: size/S

#512 Set the absolute path of the integration-test.sh script.
  benchmark.sh
Labels: size/XS

#514 Tighten up the timing around Dockerfile commands.
  pkg/executor/build.go
Labels: size/XS

#515 Reorder the Dockerfile for faster iterations.
  deploy/Dockerfile
  deploy/Dockerfile_debug
Labels: size/XS

#517 Simplify snapshotting.
  pkg/snapshot/snapshot.go
Labels: size/S

#522 Refactor our credential fetching to only get k8s credentials if we ar…
  pkg/cache/cache.go
  pkg/creds/creds_darwin.go
  pkg/creds/creds_linux.go
  pkg/executor/push.go
  pkg/util/image_util.go
Labels: size/L

#526 Make benchmark runs push to a separate namespace.
  benchmark.sh
Labels: size/XS

#527 Move the benchmark files from /workspace to their own mounted volume …
  benchmark.sh
  integration/images.go
Labels: size/S

#513 Fill in missing docs for --insecure
  README.md
Labels: needs-ok-to-test, size/XS

#523 Upload benchmarks to GCS.
  integration/gcs.go
  integration/images.go
  integration/integration_test.go
Labels: size/S

#538 Fix the time format we use to upload to GCS.
  integration/images.go
Labels: size/XS

#541 Log the output from uploading files to GCS.
  integration/gcs.go
Labels: size/XS

#525 Change cache key calculation to be more reproducible.
  integration/dockerfiles/Dockerfile_test_cache
  pkg/executor/build.go
  pkg/util/fs_util.go
  pkg/util/tar_util.go
  pkg/util/util.go
Labels: size/M

#543 Actually fix the paths for benchmark uploading during integration tes…
  integration/gcs.go
  integration/images.go
Labels: size/XS

#544 Only log the hour of the benchmark run.
  integration/images.go
Labels: size/XS

#546 Fix a bug in snapshotting with multi-stage images.
  integration/dockerfiles/Dockerfile_test_multistage
  pkg/executor/build.go
  pkg/executor/build_test.go
Labels: size/S
