Repository GoogleContainerTools/kaniko, pull requests merged in 2019-08, with the labels that each got.

#452 Create cache directory if it doesn't already exist
  cmd/warmer/cmd/root.go
  pkg/cache/cache.go
  pkg/cache/warm.go
Labels: size/XS

#730 Document how to build from git reference
  README.md
Labels: documentation

#497 Include warmer in debug image
  deploy/Dockerfile_debug
Labels: needs-ok-to-test, size/XS
