Repository GoogleContainerTools/kaniko, pull requests merged in 2019-02, with the labels that each got.

#551 Generate the config.json from gcloud rather than relying on a hardcod…
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
  files/config.json
  integration/dockerfiles/Dockerfile_onbuild_base
  integration/images.go
  integration/integration_test.go
Labels: size/M

#549 Fix issues with layer caching, noPush and tarPath
  pkg/executor/push.go
Labels: needs-ok-to-test, size/S

#554 Fix a bug in volume handling for multi-stage images.
  integration/dockerfiles/Dockerfile_test_volume_3
  integration/integration_test.go
  pkg/util/fs_util.go
Labels: size/S

#555 This fixes a bug in the interaction between volumes in base images
  integration/dockerfiles/Dockerfile_test_volume_4
  pkg/commands/volume.go
  pkg/executor/build.go
  pkg/util/fs_util.go
Labels: size/M

#553 let's return errors when warming a cache
  pkg/cache/warm.go
Labels: needs-ok-to-test, size/S

#556 Cut 0.9.0 release.
  CHANGELOG.md
  Makefile
Labels: size/XS

#558 Refactor the build loop to fetch stagebuilders earlier.
  pkg/executor/build.go
Labels: size/M

#559 Refactor whitelist handling.
  pkg/constants/constants.go
  pkg/snapshot/snapshot.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: size/L

#557 Speed up workdir by always returning an empty filelist (rather than a…
  pkg/commands/workdir.go
  pkg/commands/workdir_test.go
Labels: size/M

#561 Refactor snapshotting
  pkg/snapshot/layered_map.go
  pkg/snapshot/snapshot.go
Labels: size/M

#560 Stop storing a separate cache hash.
  pkg/snapshot/layered_map.go
  pkg/snapshot/layered_map_test.go
Labels: size/S

#565 Add missing tests for bucket util
  pkg/util/bucket_util.go
  pkg/util/bucket_util_test.go
  testutil/util.go
Labels: needs-ok-to-test, size/M

#564 Make the run_in_docker script support caching.
  run_in_docker.sh
Labels: size/S

#569 Fix typo in error message
  pkg/cache/cache.go
Labels: needs-ok-to-test, size/XS

#571 Log "Skipping paths under..." to debug
  pkg/snapshot/snapshot.go
Labels: size/XS

#570 Look for manifests in the local cache next to the full images.
  pkg/cache/cache.go
  pkg/executor/build.go
  pkg/util/image_util.go
Labels: size/M

#573 README.md: update Buildah description
  README.md
Labels: needs-ok-to-test, size/S

#576 Update the cache warmer to also save manifests.
  pkg/cache/warm.go
Labels: size/S

#586 README.me: update Buildah description
  README.md
Labels: needs-ok-to-test, size/S

#580 Environment variables should be replaced in URLs in ADD commands.
  integration/dockerfiles/Dockerfile_test_add
  pkg/commands/add.go
  pkg/util/command_util.go
  pkg/util/command_util_test.go
Labels: size/L
