Repository GoogleContainerTools/kaniko, pull requests merged in 2020-01, with the labels that each got.

#939 Tidy dependencies
  go.mod
  go.sum
  vendor/github.com/docker/docker/pkg/archive/example_changes.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/google/go-github/github/gen-accessors.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: cla: yes

#955 Fixes #950 integration test failing on go 1.13
  integration/integration_test.go
Labels: cla: yes

#945 Fix #944 include docker-credential-acr-linux
  deploy/Dockerfile
Labels: cla: yes

#954 Move hash bang to first line.
  benchmark.sh
  integration-test.sh
  run_in_docker.sh
Labels: cla: yes

#949 Fix #948 update valid license years
  hack/boilerplate/boilerplate.py
Labels: cla: yes, kokoro:run

#927 Fix #926 cache warmer and method signature
  pkg/cache/cache.go
  pkg/cache/doc_test.go
  pkg/cache/errors.go
  pkg/cache/warm.go
  pkg/cache/warm_test.go
  pkg/fakes/image.go
  pkg/util/image_util.go
Labels: cla: yes

#965 Allow setting serviceAccount in integration test
  integration-test.sh
  integration/images.go
  integration/integration_test.go
Labels: cla: yes

#961 Fix #647 Copy dir permissions
  go.mod
  go.sum
  vendor/github.com/otiai10/copy/.gitignore
  vendor/github.com/otiai10/copy/copy.go
  vendor/github.com/otiai10/copy/go.mod
  vendor/github.com/otiai10/copy/go.sum
  vendor/modules.txt
Labels: cla: yes

#967 Clean code (Condition is always 'false' because 'err' is always 'nil' ).
  pkg/util/image_util.go
Labels: cla: yes

#964 Fix bug with docker compatibility ArgsEscaped
  integration-test.sh
  integration/images.go
  integration/integration_test.go
  pkg/commands/cmd.go
Labels: cla: yes

#941 Support for private registries in the cache warmer
  deploy/Dockerfile_warmer
  pkg/cache/warm.go
Labels: cla: yes

#972 release v0.16.0
  CHANGELOG.md
  Makefile
Labels: cla: yes

#943 Fix #942 COPY or ADD to symlink destination breaks image
  pkg/commands/copy.go
  pkg/commands/copy_test.go
  pkg/util/command_util.go
  pkg/util/command_util_test.go
Labels: cla: yes

#792 Fix Ability for ADD to unTar a file
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#983 Fix #519 capital letter in stage names
  integration/dockerfiles/Dockerfile_test_from_multistage_capital
  pkg/dockerfile/dockerfile.go
Labels: cla: yes

#981 Fix #940 set modtime when extracting
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#980 Prefer platform that is currently running for pulling remote images and kaniko binary Makefile target
  Makefile
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
  pkg/util/image_util.go
  pkg/util/util.go
Labels: cla: yes

#979 Run integration tests in Travis CI
  .travis.yml
  integration/dockerfiles/Dockerfile_onbuild_base
  integration/dockerfiles/Dockerfile_test_add
  integration/dockerfiles/Dockerfile_test_cache
  integration/dockerfiles/Dockerfile_test_cache_install
  integration/dockerfiles/Dockerfile_test_cmd
  integration/dockerfiles/Dockerfile_test_env
  integration/dockerfiles/Dockerfile_test_expose
  integration/dockerfiles/Dockerfile_test_extract_fs
  integration/dockerfiles/Dockerfile_test_label
  integration/dockerfiles/Dockerfile_test_meta_arg
  integration/dockerfiles/Dockerfile_test_metadata
  integration/dockerfiles/Dockerfile_test_multistage
  integration/dockerfiles/Dockerfile_test_run
  integration/dockerfiles/Dockerfile_test_run_2
  integration/dockerfiles/Dockerfile_test_user
  integration/dockerfiles/Dockerfile_test_user_run
  integration/dockerfiles/Dockerfile_test_volume
  integration/dockerfiles/Dockerfile_test_volume_2
  integration/dockerfiles/Dockerfile_test_workdir
  integration/images.go
  integration/integration_test.go
  integration/replace-gcr-with-local-registry.sh
Labels: cla: yes

#973 Fix issue #704
  go.mod
  go.sum
  integration/dockerfiles/Dockerfile_test_deleted_file_cached
  pkg/commands/copy.go
  pkg/commands/run.go
  pkg/mocks/go-containerregistry/mockv1/mocks.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: cla: yes

#994 Change loglevel for extractedFiles to debug. Fixes #901
  pkg/commands/copy.go
Labels: cla: yes

#975 Fix #506 add option additional-whitelist
  README.md
  cmd/executor/cmd/root.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#995 Fix home and group set for user command
  pkg/commands/run.go
  pkg/commands/user.go
  pkg/commands/user_test.go
Labels: candidate-release, cla: yes

#971 Fix Symlinks not being copied across stages
  integration/dockerfiles/Dockerfile_test_copy_symlink
  pkg/commands/copy.go
  pkg/executor/build.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: candidate-release, cla: yes

#1004 Remove debug tag being built for every push to master
  deploy/cloudbuild.yaml
Labels: cla: yes

#990 Fixes #988 run_in_docker.sh only works with gcr.io
  run_in_docker.sh
Labels: cla: yes

#1009 Revert additional whitelist flag
  README.md
  cmd/executor/cmd/root.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#1011 Add flag to --whitelist-var-run set to true to preserver default kani…
  README.md
  cmd/executor/cmd/root.go
  pkg/config/options.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#854 Fix caching to respect .dockerignore
  pkg/executor/build.go
  pkg/executor/build_test.go
  pkg/executor/composite_cache.go
  pkg/executor/composite_cache_test.go
  pkg/util/command_util.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: candidate-release, cla: yes

#1015 Change loglevel for whiteouts to debug
  pkg/snapshot/snapshot.go
Labels: cla: yes

#1000 whitelist /tmp/apt-key-gpghome.* directory
  pkg/snapshot/layered_map.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: candidate-release, cla: yes

#993 Expand build argument from environment when no value specified
  cmd/executor/cmd/root.go
  cmd/executor/cmd/root_test.go
  integration/dockerfiles/Dockerfile_test_arg_secret
  integration/images.go
Labels: candidate-release, cla: yes
