Repository GoogleContainerTools/kaniko, pull requests merged in 2020-03, with the labels that each got.

#1093 fix #1092 TestRelativePaths
  integration/dockerfiles/Dockerfile_relative_copy
  integration/images.go
  integration/integration_test.go
Labels: cla: yes

#1088 add integration tests with their own context
  integration-test.sh
  integration/dockerfiles-with-context/issue-1020/Dockerfile
  integration/dockerfiles-with-context/issue-1020/package-lock.json
  integration/dockerfiles-with-context/issue-1020/package.json
  integration/dockerfiles-with-context/issue-721/Dockerfile
  integration/dockerfiles-with-context/issue-721/test.txt
  integration/dockerfiles-with-context/issue-774/Dockerfile
  integration/dockerfiles-with-context/issue-774/test-file
  integration/images.go
  integration/integration_with_context_test.go
Labels: cla: yes

#1086 check for filepath.Walk error everywhere
  pkg/commands/copy_test.go
  pkg/util/fs_util.go
Labels: cla: yes

#1103 fixing docker run command in README.md
  README.md
Labels: cla: yes

#1090 Split travis integration tests
  .travis.yml
  Makefile
  misc-integration-test.sh
  travis-setup.sh
Labels: cla: yes

#1105 fix user metadata set to USER:GROUP if group string is not set
  integration/dockerfiles/Dockerfile_test_user_without_grp
  pkg/commands/run.go
  pkg/commands/user.go
  pkg/commands/user_test.go
Labels: cla: yes

#1072 integration: test case for HOME
  integration/dockerfiles/Dockerfile_test_user_home
  pkg/commands/run.go
  pkg/commands/run_test.go
  pkg/commands/user_test.go
Labels: cla: yes

#1108 release notes for v0.18.0
  CHANGELOG.md
  Makefile
Labels: cla: yes

#1113 fix resolve link for dirs with trailing /
  pkg/commands/copy.go
  pkg/executor/composite_cache.go
  pkg/filesystem/resolve.go
  pkg/filesystem/resolve_test.go
  pkg/util/fs_util.go
Labels: cla: yes

#1114 Add more tests for Copy and some fixes.
  integration/dockerfiles/Dockerfile_test_copy_symlink
  pkg/commands/add.go
  pkg/commands/copy.go
  pkg/commands/copy_test.go
  pkg/executor/build.go
  pkg/filesystem/resolve.go
  pkg/snapshot/snapshot.go
  pkg/util/.editorconfig
  pkg/util/command_util.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
  testutil/util.go
Labels: cla: yes, kokoro:run

#1037 Allow user to provide registry certificate
  cmd/executor/cmd/root.go
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
  pkg/config/args.go
  pkg/config/args_test.go
  pkg/config/options.go
  pkg/executor/push.go
  pkg/executor/push_test.go
Labels: candidate-release-0.19.0, cla: yes

#1075 executor: add --label flag
  README.md
  cmd/executor/cmd/root.go
  integration/integration_test.go
  pkg/config/options.go
  pkg/executor/build.go
  pkg/executor/build_test.go
Labels: candidate-release-0.19.0, cla: yes

#1124 Travis k8s integration test
  .travis.yml
  Makefile
  integration-test.sh
  integration/images.go
  integration/k8s-job.yaml
  integration/k8s_test.go
  scripts/integration-test.sh
  scripts/minikube-setup.sh
  scripts/misc-integration-test.sh
  scripts/test.sh
  scripts/travis-setup.sh
Labels: cla: yes

#1128 fix: credential typo
  pkg/buildcontext/azureblob.go
Labels: cla: yes

#1134 Add support to --chown flag to ADD command (Issue #57)
  integration/dockerfiles-with-context/issue-57/Dockerfile
  integration/dockerfiles-with-context/issue-57/a.txt
  integration/dockerfiles-with-context/issue-57/b.txt
  pkg/commands/add.go
  pkg/commands/copy.go
  pkg/commands/copy_test.go
  pkg/util/command_util.go
  pkg/util/command_util_test.go
  pkg/util/fs_util.go
Labels: cla: yes

#1135 Make cloudbuild.yaml re-usable for anyone
  .gcloudignore
  deploy/cloudbuild.yaml
Labels: cla: yes

#1115 feat: add support of local '.tar.gz' file inside the kaniko container
  README.md
  cmd/executor/cmd/root.go
  integration/integration_test.go
  pkg/buildcontext/buildcontext.go
  pkg/buildcontext/tar.go
  pkg/buildcontext/tar_test.go
Labels: candidate-release-0.19.0, cla: yes

#1098 Migrate to golang 1.14
  .travis.yml
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
  go.mod
  hack/linter.sh
  vendor/modules.txt
Labels: candidate-release-0.19.0, cla: yes

#1085 remove build args from composite key and replace all build args
  pkg/executor/build.go
  pkg/executor/build_test.go
  pkg/executor/fakes.go
Labels: candidate-release-0.19.0, cla: yes

#1121 Use the correct name for acr helper
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
Labels: cla: yes

#1141 Update README on running in Docker
  README.md
Labels: cla: yes

#1143 unit tests on copy + chown
  go.mod
  go.sum
  pkg/commands/add.go
  pkg/commands/copy.go
  pkg/commands/copy_test.go
  pkg/util/command_util.go
  testutil/util.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: cla: yes

#1145 release v0.19.0
  CHANGELOG.md
  Makefile
Labels: cla: yes

#1147 small perf optimizing. Only remove whiteout path if it needs to be included in base image
  pkg/util/fs_util.go
Labels: cla: yes

#1140 Add ability to use public GCR repos without being authenticated
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
  integration/integration_test.go
  integration/migrate_gcr.go
  pkg/executor/push.go
  pkg/executor/push_test.go
Labels: cla: yes

#1130 Set image platform for any build
  pkg/executor/build.go
Labels: cla: yes

#1155 Refactor Kaniko to test across multistages
  pkg/commands/commands.go
  pkg/commands/copy.go
  pkg/commands/copy_test.go
  pkg/commands/run.go
  pkg/config/init.go
  pkg/executor/build.go
  pkg/executor/build_test.go
  pkg/executor/copy_multistage_test.go
  pkg/filesystem/resolve.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
  pkg/util/command_util.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
  pkg/util/tar_util.go
Labels: cla: yes

#1168 32bit overflow fix
  pkg/util/fs_util.go
Labels: cla: yes
