Repository GoogleContainerTools/kaniko, pull requests merged in 2020-02, with the labels that each got.

#1016 fix test flake
  pkg/util/fs_util_test.go
Labels: cla: yes

#1018 Release v0.17.0
  CHANGELOG.md
  Makefile
Labels: cla: yes

#962 Support COPY --chown flag
  cmd/executor/cmd/root.go
  pkg/commands/copy.go
  pkg/commands/run.go
  pkg/util/command_util.go
  pkg/util/command_util_test.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: candidate-release, cla: yes

#1025 update initialWhitelist instead of whitelist
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#1026 release 0.17.01
  CHANGELOG.md
  Makefile
Labels: cla: yes

#1030 fix flake TestRun/Dockerfile_test_copy_symlink
  integration/dockerfiles/Dockerfile_test_copy_symlink
  pkg/commands/copy.go
  pkg/executor/build.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#1014 Allow contributors to launch integration tests against local registry
  .travis.yml
  DEVELOPMENT.md
  integration/config.go
  integration/images.go
  integration/integration_test.go
  integration/migrate_gcr.go
  integration/replace-gcr-with-local-registry.sh
Labels: cla: yes, kokoro:run

#1031 set log format using a flag
  cmd/executor/cmd/root.go
  cmd/warmer/cmd/root.go
  pkg/constants/constants.go
  pkg/logging/logging.go
  pkg/util/util.go
Labels: cla: yes, kokoro:run

#1034 update instructions for running integration tests
  DEVELOPMENT.md
Labels: cla: yes

#882 Do not recompute layers retrieved from cache
  pkg/commands/cache.go
  pkg/commands/cache_test.go
  pkg/commands/copy.go
  pkg/commands/copy_test.go
  pkg/commands/run.go
  pkg/commands/run_test.go
  pkg/executor/build.go
Labels: candidate-release, cla: yes

#1027 refactor copy.chown code and add more tests
  pkg/commands/copy.go
  pkg/commands/copy_test.go
Labels: cla: yes

#1040 More idiomatic logging config
  cmd/executor/cmd/root.go
  cmd/warmer/cmd/root.go
  pkg/logging/logging.go
Labels: cla: yes

#1043 Fix example pod.yml to not mount to root
  examples/pod.yaml
Labels: cla: yes

#1046 add design proposal template
  docs/design_proposals/design-proposal-template.md
Labels: cla: yes

#1044 Document that this tool is not officially supported by Google
  README.md
Labels: cla: yes

#1032 Ensure image SHA stays consistent when layer contents haven't changed
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
  pkg/util/tar_util.go
Labels: cla: yes

#1055 separate travis into multiple jobs for parallelization
  .travis.yml
Labels: cla: yes

#836 root: add --registry-mirror flag
  README.md
  cmd/executor/cmd/root.go
  integration/dockerfiles/Dockerfile_registry_mirror
  integration/integration_test.go
  pkg/config/options.go
  pkg/util/image_util.go
  pkg/util/image_util_test.go
Labels: candidate-release, cla: yes

#1048 design proposal 01: filesystem resolution
  docs/design_proposals/filesystem-resolution-proposal-01.md
Labels: cla: yes

#1068 Fix #1067 - image no longer available
  integration/dockerfiles/Dockerfile_test_replaced_symlinks
Labels: cla: yes

#1066 Update filesystem proposal status to Reviewed
  docs/design_proposals/filesystem-resolution-proposal-01.md
Labels: cla: yes

#1074 Fix #1020 os.Chtimes invalid arg
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#1069 Resolve filepaths before scanning for changes
  integration/dockerfiles/Dockerfile_test_issue_1039
  pkg/filesystem/resolve.go
  pkg/filesystem/resolve_test.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
  pkg/util/fs_util.go
Labels: cla: yes

#1049 Refactor integration image built
  integration/images.go
  integration/integration_test.go
Labels: cla: yes

#1077 test: refactor container-diff call
  integration/integration_test.go
Labels: cla: yes

#1060 Fixed typo in README.md
  README.md
Labels: cla: yes
