Repository GoogleContainerTools/kaniko, pull requests merged in 2020-06, with the labels that each got.

#1289 Instructions for using stdin with kubectl
  README.md
Labels: cla: yes

#1295 rename whitelist to ignorelist
  cmd/executor/cmd/root.go
  deploy/Dockerfile_debug
  docs/design_proposals/filesystem-resolution-proposal-01.md
  integration/dockerfiles/Dockerfile_test_add
  integration/dockerfiles/Dockerfile_test_multistage
  integration/integration_test.go
  pkg/commands/volume.go
  pkg/config/init.go
  pkg/config/options.go
  pkg/constants/constants.go
  pkg/dockerfile/dockerfile_test.go
  pkg/executor/build.go
  pkg/executor/composite_cache.go
  pkg/executor/copy_multistage_test.go
  pkg/filesystem/resolve.go
  pkg/filesystem/resolve_test.go
  pkg/snapshot/snapshot.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes

#1285 Added integration test for multi level argument
  integration/dockerfiles/Dockerfile_test_arg_two_level
  integration/integration_test.go
Labels: cla: yes

#1254 add 64 busybox
  deploy/Dockerfile_debug
Labels: candidate-release-0.23.0, cla: yes

#1260 Resolving nested meta ARGs
  pkg/dockerfile/dockerfile.go
  pkg/dockerfile/dockerfile_test.go
Labels: candidate-release-0.23.0, cla: yes

#1296 prepare for release v0.23.0
  CHANGELOG.md
  Makefile
Labels: cla: yes

#1283 [Perf] Reduce loops over files when taking FS snapshot.
  pkg/snapshot/snapshot.go
Labels: candidate-0.24.0, cla: yes

#1302 check file changed in loop
  pkg/snapshot/layered_map.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/snapshot_test.go
Labels: cla: yes

#1301 Add redo snapshotter.
  integration/dockerfiles/Dockerfile_test_run_redo
  integration/images.go
  pkg/constants/constants.go
  pkg/executor/build.go
  pkg/util/util.go
Labels: cla: yes

#1307 Fix docker-credential-gcr owner and group id
  deploy/Dockerfile
  deploy/Dockerfile_debug
Labels: cla: yes

#1323 Fix README.md
  README.md
Labels: cla: yes

#1320 feat: recurse submodules
  pkg/buildcontext/git.go
Labels: cla: yes

#1328 Add pkg.dev to automagic config file population
  pkg/executor/push.go
  pkg/executor/push_test.go
Labels: cla: yes

#1336 release v0.24.0
  CHANGELOG.md
  Makefile
Labels: cla: yes
