Repository GoogleContainerTools/kaniko, pull requests merged in 2020-08, with the labels that each got.

#1379 fix use new run marker
  Makefile
  pkg/commands/run_marker.go
Labels: cla: yes

#1374 Use current platform when fetching image in warmer
  pkg/cache/warm.go
Labels: cla: yes

#1364 executor image: fix USER environment variable
  deploy/Dockerfile
Labels: cla: yes

#1358 Format json & yaml in README
  README.md
Labels: cla: yes

#1318 feat: accept GIT_TOKEN
  README.md
  pkg/buildcontext/git.go
  pkg/buildcontext/git_test.go
Labels: cla: yes, kokoro:run

#1153 Checkout a specific git commit
  README.md
  pkg/buildcontext/git.go
Labels: cla: yes, needs-unit-tests

#1383 new implementation for run
  Makefile
  pkg/commands/run_marker.go
  pkg/util/fs_util.go
Labels: cla: yes

#1342 Set correct PATH for exec form
  pkg/commands/run.go
Labels: candidate-release, cla: yes

#1322 feat: new git flags
  cmd/executor/cmd/root.go
  pkg/buildcontext/buildcontext.go
  pkg/buildcontext/git.go
  pkg/config/options.go
  pkg/config/options_test.go
Labels: candidate-release, cla: yes

#1385 Added instructions to use gcr without kubernetes
  README.md
Labels: cla: yes

#1388 prepare for v1.0.0 release
  CHANGELOG.md
  Makefile
Labels: cla: yes

#1398 Fix links on README
  README.md
Labels: cla: yes

#1394 Update README.md re: layer cache behavior
  README.md
Labels: cla: yes

#1397 Add func to append to ignorelist
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
Labels: cla: yes
