Repository GoogleContainerTools/kaniko, pull requests merged in 2021-12, with the labels that each got.

#1800 Fix syntax error in release.yaml
  .github/workflows/release.yaml
Labels: cla: yes

#1831 Add documentation on pushing to ACR
  README.md
Labels: cla: yes

#1811 Update readme insecure flags
  README.md
Labels: cla: yes

#1809 Use pax tar format
  pkg/util/tar_util.go
  pkg/util/tar_util_test.go
Labels: cla: yes

#1804 Fix broken anchor link
  README.md
Labels: cla: yes

#1796 include auth for FetchOptions
  pkg/buildcontext/git.go
Labels: cla: yes

#1813 Fix possible nil pointer derefence in fs_util.go
  pkg/util/fs_util.go
Labels: cla: yes

#1825 Fix typo
  README.md
Labels: cla: yes

#1725 Fix copying ownership
  integration/dockerfiles-with-context/issue-1315/Dockerfile
  pkg/util/fs_util.go
Labels: cla: yes

#1823 Fix regression: can fetch branches and tags references without specifying commit hashes for private git repository used as context
  pkg/buildcontext/git.go
Labels: cla: yes, needs-integration-test

#1728 tar: read directly from stdin
  pkg/buildcontext/tar.go
  pkg/util/fs_util.go
  pkg/util/fs_util_test.go
  pkg/util/tar_util.go
Labels: cla: yes

#1693 fix: ARG/ENV used in script does not invalidate build cache (#1688)
  pkg/executor/build.go
  pkg/executor/build_test.go
Labels: needs-rebase, cla: yes
