Repository GoogleContainerTools/kaniko, pull requests merged in 2021-10, with the labels that each got.

#1741 Fix executor Dockerfile, which wasn't building
  deploy/Dockerfile
Labels: kokoro:run, cla: yes

#1770 disable github action workflow on push to master
  .github/workflows/integration-mis.yaml
  .github/workflows/integration-run-tests.yaml
  .github/workflows/integration_k8_tests.yaml
  .github/workflows/intergration-layers-tests.yaml
  .github/workflows/unit-tests.yaml
Labels: cla: yes

#1776 fix dockerfiles for deploy gcr binary
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
Labels: cla: yes

#1780 Run docker_credentials_gcr in warmer
  cmd/warmer/cmd/root.go
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
  hack/boilerplate/boilerplate.py
  pkg/executor/push.go
  pkg/executor/push_test.go
  pkg/util/gcr_util.go
  pkg/util/gcr_util_test.go
Labels: cla: yes

#1781 Revert ppce4 and other unintentional changes
  .github/workflows/release.yaml
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
Labels: cla: yes

#1785 chore: add release workflow on pr
  .github/workflows/pr_release.yaml
  .github/workflows/release.yaml
  deploy/Dockerfile
  deploy/Dockerfile_debug
  deploy/Dockerfile_warmer
Labels: cla: no

#1765 git: accept explicit commit hash for git context
  hack/linter.sh
  integration/integration_test.go
  pkg/buildcontext/git.go
  scripts/test.sh
Labels: cla: yes

#1794 Revert "Support mirror registries with path component (#1707)"
  .github/workflows/release.yaml
  integration/integration_test.go
  pkg/image/remote/remote.go
Labels: cla: yes
